name: "E2E test"
on: [push]

jobs:
  check_install:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [macos-latest]
        xcode: ["10.0", "10.1", "10.2.1", "10.3", "11.0", "11.1"]

    runs-on: ${{ matrix.os }}
    env:
      XCODE_INSTALL_USER: ${{ secrets.XCODE_INSTALL_USER }}
      XCODE_INSTALL_PASSWORD: ${{ secrets.XCODE_INSTALL_PASSWORD }}
    steps:
    # Show env
    - name: Show macOS version
      run: sw_vers
    - name: Show ruby version
      run: ruby --version
      
    # Prepare
    - uses: actions/checkout@v1
    - name: Setup bundler ~> 1.7
      run: |
        gem uninstall bundler
        gem install bundler -v "~> 1.7"
    - run: bundle install -j4 --clean --path=vendor
    - run: bundle exec xcversion update
    - run: bundle exec xcversion uninstall ${{ matrix.xcode }}
    - name: Show installed versions before install
      run: bundle exec xcversion installed

    # Exec
    - run: bundle exec xcversion install ${{ matrix.xcode }}

    # Check
    - name: Show installed versions after install
      run: bundle exec xcversion installed
    - name: Check Xcode installation was successful
      run: bundle exec xcversion installed | grep "${{ matrix.xcode }}"
